apiVersion: v1
data:
  server-name-hash-bucket-size: "512"
  ssl-protocols: "TLSv1.2"
  proxy-read-timeout: "300" 
  proxy-send-timeout: "300"
kind: ConfigMap
metadata:
  name: nginx-ingress-conf
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ilb-rc
#  annotations:
#    ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app: nginx-ilb
spec:
  replicas: 1
  selector:
    app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.3
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
        - /nginx-ingress-controller
        - --default-backend-service=default/default-http-backend
        #- --running-in-cluster=true
        - --healthz-port=9999
        - --configmap=$(POD_NAMESPACE)/nginx-ingress-conf
      hostNetwork: true
