# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workbench
subjects:
- kind: ServiceAccount
  name: workbench
  namespace: default
roleRef:
  kind: ClusterRole
  name: workbench
  apiGroup: rbac.authorization.k8s.io
