apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ndslabs-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - www.{{ DOMAIN }}
    secretName: ndslabs-tls-secret
  rules:
  - host: www.{{ DOMAIN }}
    http:
      paths:
      - path: /api
        backend:
          serviceName: ndslabs-apiserver
          servicePort: 30001
      - path: /
        backend:
          serviceName: ndslabs-webui
          servicePort: 80
