apiVersion: v1
kind: Service
metadata:
  name: ndslabs-logserve
  labels:
    component: ndslabs-logserve
spec:
  selector:
    component: ndslabs-webui
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ndslabs-webui
  labels:
    component: ndslabs-webui
spec:
  selector:
    component: ndslabs-webui
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ndslabs-webui
spec:
  replicas: 1
  selector:
    component: ndslabs-webui
  template:
    metadata:
      labels:
        component: ndslabs-webui
    spec:
      volumes:
       - hostPath:
            path: "/home/core/ndslabs/gui/"
         name: src
       - hostPath:
            path: "/home/core/ndslabs/gui/logserve/"
         name: logserve
      containers:
      - name: logserve
        image: ndslabs/logserve
        imagePullPolicy: Always
        volumeMounts:
          - name: logserve
            mountPath: /home/logserve
        ports:
        - containerPort: 3000
          protocol: TCP
      - name: webserver
        image: ndslabs/angular-ui:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: src
            mountPath: "/home/"
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: APISERVER_HOST
            value: "{{ APISERVER_HOST }}"
          - name: APISERVER_PORT
            value: "{{ APISERVER_PORT }}"
          - name: APISERVER_PATH
            value: "/api"
          - name: APISERVER_SECURE
            value: "{{ APISERVER_SECURE }}"
          - name: SUPPORT_EMAIL
            value: "{{ SUPPORT_EMAIL }}"
