apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: cluster-backup
spec:
#  suspend: true
#  schedule: "*/1 * * * *"
  schedule: "0 0 0 * *"
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true
          restartPolicy: OnFailure
          containers:
#          - image: ndslabs/cluster-backup:latest
            image: bodom0015/cluster-backup:NDS-886-manual
            imagePullPolicy: Always
            name: cluster-backup
            command: [ "./backup.sh" ]
            env:
             - name: CLUSTER_ID
               valueFrom:
                 configMapKeyRef:
                   name: ndslabs-config
                   key: workbench.domain
             - name: ETCD_HOST
               value: $(NDSLABS_ETCD_SERVICE_HOST)
             - name: ETCD_PORT
               value: $(NDSLABS_ETCD_SERVICE_PORT)
             - name: BACKUP_SRC
               value: "/var/glfs"
             - name: BACKUP_DEST
               value: /ndsbackup
             - name: BACKUP_HOST
               value: 
             - name: BACKUP_USER
               value: 
             - name: BACKUP_KEY
               value: "/etc/backup-key/ssh-privatekey"
            volumeMounts:
              - name: clusterdata
                mountPath: /var/glfs
              - name: backupkey
                readOnly: true
                mountPath: /etc/backup-key/
          volumes:
            - name: clusterdata
              hostPath:
                  path: /var/glfs
            - name: backupkey
              secret:
                secretName: backup-key
                defaultMode: 0600
